/**
 * @famgia/omnify-cli - AI Guide Generator
 *
 * Generates base Omnify documentation (CLAUDE.md + core guides).
 * Plugin-specific guides are generated by respective plugins.
 */

import { existsSync, writeFileSync, mkdirSync, readdirSync, readFileSync, copyFileSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { OmnifyPlugin } from '@famgia/omnify-types';

/**
 * CLAUDE.md content for project root
 * Uses Claude Code's official memory format with @imports
 */
const CLAUDE_MD = `# Omnify Project

This project uses **Omnify** for schema-driven code generation.

## Quick Reference

- **Schema Guide**: @.claude/omnify/guides/omnify/schema-guide.md
- **Config Guide**: @.claude/omnify/guides/omnify/config-guide.md

## Commands

\`\`\`bash
npx omnify generate    # Generate code from schemas
npx omnify validate    # Validate schemas
php artisan migrate    # Run database migrations
\`\`\`

## Critical Rules

### ⛔ DO NOT EDIT Auto-Generated Files
- \`database/migrations/omnify/**\` - Regenerated on \`npx omnify generate\`
- \`app/Models/OmnifyBase/**\` - Base models (extend, don't edit)
- \`app/Http/Requests/OmnifyBase/**\` - Base requests
- \`app/Http/Resources/OmnifyBase/**\` - Base resources

### ✅ Schema-First Workflow
1. Edit YAML schema in \`schemas/\`
2. Run \`npx omnify generate\`
3. Run \`php artisan migrate\`

**NEVER use \`php artisan make:migration\`** - Always use schemas!

## Documentation Structure

\`\`\`
.claude/
├── CLAUDE.md              # This file (root pointer)
├── rules/                 # Claude Code rules (path-specific)
│   └── omnify/*.md
└── omnify/                # Detailed guides
    ├── guides/
    │   ├── omnify/        # Schema & config docs
    │   ├── laravel/       # Laravel patterns
    │   └── react/         # React patterns
    ├── workflows/         # Step-by-step workflows
    └── agents/            # AI agent prompts
\`\`\`

## Individual Preferences

Add your personal preferences in \`CLAUDE.local.md\` (gitignored).
`;

/**
 * Copies core Omnify guides (schema-guide, config-guide) to .claude/omnify/guides/omnify/
 */
function copyOmnifyGuides(rootDir: string): number {
  let filesWritten = 0;

  // Find @famgia/omnify package stubs directory
  const omnifyPkgPaths = [
    resolve(rootDir, 'node_modules', '@famgia', 'omnify', 'stubs', 'ai-guides', 'omnify'),
    resolve(rootDir, 'node_modules', '.pnpm', '@famgia+omnify@*', 'node_modules', '@famgia', 'omnify', 'stubs', 'ai-guides', 'omnify'),
  ];

  // Also check if we're in monorepo (packages/omnify/stubs)
  let stubsDir: string | null = null;
  for (const pkgPath of omnifyPkgPaths) {
    // Handle glob-like path for pnpm
    if (pkgPath.includes('*')) {
      const parentDir = dirname(dirname(pkgPath));
      if (existsSync(parentDir)) {
        const entries = readdirSync(parentDir);
        for (const entry of entries) {
          if (entry.startsWith('@famgia+omnify@')) {
            const testPath = join(parentDir, entry, 'node_modules', '@famgia', 'omnify', 'stubs', 'ai-guides', 'omnify');
            if (existsSync(testPath)) {
              stubsDir = testPath;
              break;
            }
          }
        }
      }
    } else if (existsSync(pkgPath)) {
      stubsDir = pkgPath;
      break;
    }
  }

  if (!stubsDir) {
    // Fallback: check via require.resolve
    try {
      const omnifyPath = dirname(require.resolve('@famgia/omnify/package.json', { paths: [rootDir] }));
      const testPath = join(omnifyPath, 'stubs', 'ai-guides', 'omnify');
      if (existsSync(testPath)) {
        stubsDir = testPath;
      }
    } catch {
      // Package not found
    }
  }

  if (!stubsDir) {
    return 0; // No stubs found
  }

  // Destination: .claude/omnify/guides/omnify/
  const destDir = resolve(rootDir, '.claude', 'omnify', 'guides', 'omnify');
  mkdirSync(destDir, { recursive: true });

  // Copy all .stub files
  const files = readdirSync(stubsDir).filter(f => f.endsWith('.stub'));
  for (const file of files) {
    const srcPath = join(stubsDir, file);
    const destPath = join(destDir, file.replace('.stub', ''));

    const content = readFileSync(srcPath, 'utf8');
    writeFileSync(destPath, content);
    filesWritten++;
  }

  return filesWritten;
}

/**
 * Generates CLAUDE.md pointer file and copies core Omnify guides.
 * Plugin-specific guides are generated by respective plugins.
 *
 * Note: Always overwrites files to ensure:
 * 1. Deleted files are restored
 * 2. Updated content from omnify packages is synced
 */
export function generateAIGuides(
  rootDir: string,
  _plugins: readonly OmnifyPlugin[]
): number {
  let filesWritten = 0;

  // Always write CLAUDE.md (overwrite to sync updates)
  const claudeMdPath = resolve(rootDir, 'CLAUDE.md');
  writeFileSync(claudeMdPath, CLAUDE_MD);
  filesWritten++;

  // Copy core Omnify guides (schema-guide.md, config-guide.md)
  filesWritten += copyOmnifyGuides(rootDir);

  return filesWritten;
}
